### ISSUE TITLE
Using the flag --no-gui with a password protected YubiKey, the password is not masked in CLI

### ISSUE THREAD

**Issue by matiasraisanen** [aripalo/vegas-credentials#28]
**Describe the bug**
I run vegas-credentials with `--no-gui` and use a password protected yubikey
It then asks me to type in my `🔑 Yubikey: Input OATH password:`, but typing the password is not masked in the CLI.

```
🔑 Yubikey: Input OATH password: 
my-super-secret-password
``` 

**System (please complete the following information):**
 - OS: Linux
 - OS Version: Zorin OS 15.3 x86_64
 - Tool Version: 0.13.5
 - Tool Installation Method: brew
 - Credential Process invoked via: aws

**Expected behavior**
Password is either not printed to CLI, or letters are masked with a `*` or similar

```
🔑 Yubikey: Input OATH password: 
***************
```

**Comment by aripalo** [comment]
Fixed in https://github.com/aripalo/vegas-credentials/pull/30 and available since version `0.13.7`.

The Yubikey OATH application password is hidden:
![vegas-input-password](https://user-images.githubusercontent.com/679146/168144890-ace1dc19-00be-4306-8086-48db80a5766e.png)

… but the OATH TOTP (MFA Token) input is still visible (if provided via CLI `stdin`):
![vegas-input-token](https://user-images.githubusercontent.com/679146/168144883-1aa7469f-78ca-4cc3-9ac9-b594d02a5956.png)
